// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {openai} from '../models';

export function Greet(arg1:string):Promise<string>;

export function SendMessage(arg1:Array<openai.ChatCompletionMessage>):Promise<string>;
